export const GET_MAKES_RECEIVED = 'GET_MAKES_RECEIVED';
export const GET_MODELS_RECEIVED = 'GET_MODELS_RECEIVED';
export const GET_CAR_OF_WEEK_RECEIVED = 'GET_CAR_OF_WEEK_RECEIVED';
export const SET_DETAIL_DATA = 'SET_DETAIL_DATA';